# A preset or -D override takes precedence over the checked-in build selection.
if(NOT DEFINED GGLBOT_DEVICE)
  if(NOT EXISTS "${DEVICE_FILE}")
    message(FATAL_ERROR "Set rlbot/device.txt to cpu or gpu, or configure with -DGGLBOT_DEVICE=cpu or gpu.")
  endif()
  file(READ "${DEVICE_FILE}" GGLBOT_DEVICE)
  string(STRIP "${GGLBOT_DEVICE}" GGLBOT_DEVICE)
endif()
if(NOT GGLBOT_DEVICE MATCHES "^(cpu|gpu)$")
  message(FATAL_ERROR "GGLBOT_DEVICE / rlbot/device.txt must be cpu or gpu.")
endif()
if(DEFINED OUTPUT_FILE)
  file(WRITE "${OUTPUT_FILE}" "${GGLBOT_DEVICE}\n")
endif()
